### ISSUE TITLE
git apply error

### ISSUE THREAD

**Issue by yucheng514** [CuSO4Gem/ohmyzsh-offline#2]
I tried according the usage in README but some error messages appeared. 

 
![Snipaste_2023-04-03_17-43-17](https://user-images.githubusercontent.com/35727398/229473352-018d2a2f-63b1-4ba4-baec-3ee84c414868.png)

How can I fix it? thx!

**Comment by CuSO4Gem** [comment]
Sorry to replay too late. I fix it. In fact, you can create a offline install shell script by edit install.sh. Just delate some cod in setup_ohmyzsh() function and add 2 lines of code.
